---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.name }}-secret
  namespace: demo-website
  labels:
    {{- include "demo-website-chart.labels" . | nindent 4 }}
spec:
  encryptedData:
    OMDB_API_KEY: AgAwyrb5ZCovpeHEHEBo7wZ65qjp8q8FbR7EYCaqHsufVh2xi6/W9oI8vr8ZhLdfNF3GIkOgbW5wjfD/71ul4GGo5QR7wXfFdpYzqQZ2kMyDNO6Ox9kQm5lxt7vdaNawL5N5BnoNvRXp13K5w8WDM2bOgS/vgvoGOAskQCKBY9WQ/VeM9Fm4N2+Gwq4CocZXkeaPeBmsuvH98/JbUTRSlehTogEPdqbqmXhGJa8itBifxWREMl8xjDbFOmMc62TYJDnL54UvrLYIksoxlptrekKOuxKn4z/VVIJECdssH7fiQhtvlllT0Oh5Rroym8LlYDUyfenhgSzxM1mpDqpMtt2yOZVWX9VO5xH6Xvm8vUp3lgJbL7TAxyraRwJxEu5ith14y/AzQZIeEsrCaQhOJQ+I7G+4qq3K8GnoZU/mRQkgVqshI35mOZXh1xwi4puKFXz/42lsFRduubLkJnvrHNflvM3AHjPebTEgo36nxoUX/PdndHhsIlG5dSH/BfehYpr4+dTLPEYcp+N9RQ5aoP5LR2Id4HLj7Ui8bScFp5kk63aZpXFf5U9KOVSCWSQMW9/6xBC6mrzGFJPhCoe9CxNnlhxwR725Fg1b473LTujoeEwkrOMUIUHpAB03DV+0FSJexKTmQqdj1o4gOs3ZwJd6zBIYmcdtm+NDA0GE8uTRrGw66eG1WkVVoV9ws/i7e57qAaUwuNLNSA==
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.name }}-secret
      namespace: demo-website
    type: Opaque
