apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  labels:
    {{- include "demo-website-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  OMDB_API_KEY: {{ .Values.appSecret.omdbApiKey | quote }}